### ISSUE TITLE
RTL languages

### ISSUE THREAD

**Issue by avishail** [mhmzdev/awesome_snackbar_content#13]
When init the material app with RTL language, the close button will switch sides and will be located wrongly.

In addition, you can see that small part of the text is begin occluded by the widget decorations. (this happens in both rlt and ltr languages)

screenshot:

![WhatsApp Image 2023-03-06 at 01 43 08](https://user-images.githubusercontent.com/10358078/222992843-857336b9-a416-47ce-b6e1-619c1b1dbced.jpeg)

**Comment by mhmzdev** [comment]
Hey
Would you share which language you are using? I'm adding support. So, just to make sure it doesn't miss your language 
thanks

**Comment by avishail** [comment]
Thanks for responding!

I'm using hebrew (use Locale("he") when constructing your MeterialApp) and you can copy paste this text: "כתובת דואל אינה קיימת. יש לבצע רישום למערכת"

I believe you can also reproduce it by wrapping everything with:

```flutter
Directionality(
    textDirection: TextDirection.ltr,
    child: AwesomeSnackbarContent(...),
)
```

This will force the direction of everything to be left-to-right regardless of the app's direction.

**Comment by mhmzdev** [comment]
Fixed, updating new version in a while

![simulator_screenshot_41217966-B845-4531-BB92-1A1DEF919040](https://user-images.githubusercontent.com/43790152/223026001-5d528c83-cbca-4e85-b237-137ac5a2b77b.png)

**Comment by avishail** [comment]
much appreciated! thanks for really awesome snack bar design :)
