### ISSUE TITLE
Any plans to add a info type to the list?

### ISSUE THREAD

**Issue by Paul-Todd** [mhmzdev/awesome_snackbar_content#2]
I was thinking an "!" type icon in blue - this fixes a common state with Snackbars where we want to just display an information snackbar

**Comment by mhmzdev** [comment]
I guess we can customise, or provide a parameter of `Widget` that could be used to replace the default Widgets in the snackbar

will update surely, incase you can do it? Feel free to create a PR

**Comment by Paul-Todd** [comment]
Happy to do so but where did you get your svg's from. I would like to use an ! one and then I am happy to code up the rest of it.

**Comment by mhmzdev** [comment]
I mostly use freepik and flaticons

**Comment by mhmzdev** [comment]
We have `ContentType` parameter that you can use to show error, success, warning or just a message.
Feel free to check that out
