### ISSUE TITLE
Minor refactoring

### ISSUE THREAD

**Issue by neliousness** [mhmzdev/awesome_snackbar_content#20]
Hey this is an awesome lib! thanks for sharing your work. 

I added some minor refactors to your code and wanted to create a pull request for it but for some reason pull requests are denied on your repo. 

Would you be willing to allow PRs or is this something you're not really interested in?  
let me know :)

**Comment by mhmzdev** [comment]
I'm not sure why you are facing this issue, because I just merged some of the PRs opened by some other devs.
Can you share me the actual error/problem?

**Comment by neliousness** [comment]
> I'm not sure why you are facing this issue, because I just merged some of the PRs opened by some other devs. Can you share me the actual error/problem?

Nevermind, i managed, sorry about that. Im going to close this issue. 

again.. sorry
