### ISSUE TITLE
In web problem

### ISSUE THREAD

**Issue by EdgarCabral** [mhmzdev/awesome_snackbar_content#22]
In the flutter web it is not displayed well, it breaks visually and the texts are not seen

**Comment by mhmzdev** [comment]
Hey, can you please share any video or SS where you are facing the issue? It's working pretty fine on all the screens.

Or you can check if you are on latest version of it or not.
Regards

https://github.com/mhmzdev/awesome_snackbar_content/assets/43790152/8472c4df-d930-41ae-862b-16e4e109dba4

**Comment by u-sour** [comment]
for me i got a small problem the icon top left side, i don't know the problem, any idea ? 

https://github.com/mhmzdev/awesome_snackbar_content/assets/145416126/5e04b916-ac4f-43d8-af42-d1f00e8e6e5f

**Comment by frankjoshua** [comment]
Any update on this. I get the same issue on web and Android.
![Screenshot_20240505_130909](https://github.com/mhmzdev/awesome_snackbar_content/assets/230666/5c97b77d-0b01-48a4-9072-f06282ca91c6)

**Comment by u-sour** [comment]
@frankjoshua for me i set top padding  on SnackBar` padding: const EdgeInsets.only(top: 48.0)` it solved this problem.

**Comment by frankjoshua** [comment]
@u-sour Thanks. Setting padding worked perfectly.

**Comment by u-sour** [comment]
@frankjoshua yeah, nvm.

**Comment by mhmzdev** [comment]
Issue has been fixed the PR closed recently
