### ISSUE TITLE
position

### ISSUE THREAD

**Issue by Jd-Moneymaker** [mhmzdev/awesome_snackbar_content#23]
i need to position this at the bottom, how do i do that ??

**Comment by mhmzdev** [comment]
If you want this to stick at bottom you can remove the `behavior: SnackBarBehavior.floating,` property. But I might make it a bit ugly as this hovering effect is by default elevation from flutter

Lemme know if this helps

**Comment by Caresle** [comment]
Hi, is there an option to put the snackbar on the top of the device? like for example `position: Position.Top`

**Comment by mhmzdev** [comment]
@Caresle You can try this effect https://github.com/mhmzdev/awesome_snackbar_content/blob/927e7b56c0cbdf9e36425cfeadda98fbe5213eb3/example/example.dart#L38

**Comment by Caresle** [comment]
Thank you
