### ISSUE TITLE
Unable to load asset

### ISSUE THREAD

**Issue by AliAltiyev** [mhmzdev/awesome_snackbar_content#24]
Unhandled Exception: Unable to load asset: "packages/awesome_snackbar_content/assets/bubbles.svg".
E/flutter ( 4825): The asset does not exist or has empty data.

**Comment by mhmzdev** [comment]
Have you tried `flutter clean` and `flutter pub get`?
Please share `flutter doctor -v`

**Comment by AliAltiyev** [comment]
Yesxi have tried flutter clean and flutter pub get scripts. 

![flutter_doctor_v](https://github.com/mhmzdev/awesome_snackbar_content/assets/100046123/cfd22faa-7b70-458c-8ede-037c16086c07)

**Comment by Altereyo** [comment]
Had the same issue. I fully reinstalled app, and it worked for me
This problem appears when you are trying to add new assets while app is running

**Comment by mhmzdev** [comment]
Closing the issue as it was not related to the package itself
