### ISSUE TITLE
Future enhancement for styling the message/title

### ISSUE THREAD

**Issue by jboss10** [mhmzdev/awesome_snackbar_content#3]
Are there any plans to allow for modification of text sizing for the title/message?

While running on Windows, the Snackbar text size is really small and quite difficult to read. It would be nice for the title/message to take in Text() widgets rather than Strings.

**Comment by jboss10** [comment]
Just poked through the first PR. It looks like someone has fine tuned and added this feature into the branch. Any chance this goes into the release anytime soon? Thank you.

**Comment by mhmzdev** [comment]
Its merged and it will be live on pub.dev once they approve it

**Comment by yashwanthambati** [comment]
Any update on this ?

**Comment by mhmzdev** [comment]
As of now, its made responsive for various screen sizes @yashwanthambati
