### ISSUE TITLE
Title and Message Size. 

### ISSUE THREAD

**Issue by alexsanderfer** [mhmzdev/awesome_snackbar_content#33]
Is there some way to change the font size of the title or message? Also, the left icon X of the snackbar and the title are too close to each others. It's probably because of the width size? 

![image](https://github.com/mhmzdev/awesome_snackbar_content/assets/33939423/5cf0129f-b4df-45ee-ae63-8c8d0ee1d67f)

**Comment by mhmzdev** [comment]
```
 double? titleFontSize,
 double? messageFontSize,
```

Above values are available in the main constructor. The Icon on the left is just an asset it won't effect any user action

**Comment by thubamamba** [comment]
Hey @mhmzdev, this is such a lovely package you'd built. Apologies for reopening this issue but I'd appreciate the assistance in the event that the text is being cut off as is the case in the screenshot. 

![Simulator Screenshot - iPhone 15 Pro Max - 2024-09-10 at 18 54 07](https://github.com/user-attachments/assets/83c7ac98-89de-45f0-8f3a-41ecbf6a55c4)

Thank you.
