### ISSUE TITLE
Bubble icon gets cropped at the top in AwesomeSnackbarContent

### ISSUE THREAD

**Issue by aleemElmozogi** [mhmzdev/awesome_snackbar_content#34]
The bubble icon in the AwesomeSnackbarContent widget is getting cropped at the top, resulting in an incomplete and visually unappealing display.

**Comment by aleemElmozogi** [comment]
![photo_2024-06-19_22-42-30](https://github.com/mhmzdev/awesome_snackbar_content/assets/53140500/f3f9ab76-4615-4bc4-8adc-60ad4d2a5da3)

**Comment by djooleean2** [comment]
If you add a 'padding' to the Snackbar like that:
`padding: const EdgeInsets.all(20),`

The padding lets enough place to display the whole icon...
