### ISSUE TITLE
Version 0.0.6 does not appear to compile with the new Desktop support

### ISSUE THREAD

**Issue by jboss10** [mhmzdev/awesome_snackbar_content#4]
I tried to compile with the latest 0.0.6 but seems either I missed something or there are some issues in the build. 

- awesome_snackbar_content.dart(33,10): error G985155F6: 'isDesktop' is a final instance variable that was initialized at the declaration.
- awesome_snackbar_content.dart(33,10): error G2E3FC805: Cannot invoke a non-'const' constructor where a const expression is expected. 
- awesome_snackbar_content.dart(34,10): error GA03AAAF0: 'xlarge' is a final instance variable that was initialized at the declaration.
- awesome_snackbar_content.dart(34,10): error G2E3FC805: Cannot invoke a non-'const' constructor where a const expression is expected. 
- awesome_snackbar_content.dart(33,10): error GA89667EF: The parameter 'isDesktop' can't have a value of 'null' because of its type 'bool', but the implicit default value is 'null'.
- awesome_snackbar_content.dart(34,10): error GA89667EF: The parameter 'xlarge' can't have a value of 'null' because of its type 'bool', but the implicit default value is 'null'.

**Comment by arindammitra06** [comment]
Same for me too !!

**Comment by mhmzdev** [comment]
Issue fixed for various screen sizes here https://github.com/mhmzdev/awesome_snackbar_content/commit/c9e9360d0cef791d4b87cd3c5d107b928a70b1b9

New package now available with `0.0.7`
