### ISSUE TITLE
top snackbar 

### ISSUE THREAD

**Issue by thorizer** [mhmzdev/awesome_snackbar_content#5]
love the design , since this package can uplift my SnackBar experience , can I uplift the SnackBar itself to the top ? 
like this package https://pub.dev/packages/top_snackbar_flutter

**Comment by AdebayoGit** [comment]
Hi, 

From the link you shared, I can see that that is not a snack bar, it is actually called a Banner. However, I believe it can be done by calling the material banner method on your scaffold messenger instead. Goodluck

**Comment by mhmzdev** [comment]
New version has been updated with the use of `materialBanner`
