### ISSUE TITLE
Assets are buged

### ISSUE THREAD

**Issue by moneebshammout** [mhmzdev/awesome_snackbar_content#7]
I get these errors when showing a snack bar.

Unable to load asset: packages/awesome_snackbar_content/assets/back.svg
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by SVG ═══════════════════════════════════════════════
Unable to load asset: packages/awesome_snackbar_content/assets/types/success.svg
════════════════════════════════════════════════════════════════════════════════

I also tried to open the assets in GitHub it seems they are not showing.

**Comment by jochy** [comment]
A workaround is to rollback the version to `0.0.9` : `awesome_snackbar_content: 0.0.9`

**Comment by mhmzdev** [comment]
Its working pretty fine for `0.1.0`
Can you please try `flutter clean; flutter pub get`

Let me know if this still persists

**Comment by mhmzdev** [comment]
Updated `0.1.1`
